[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.24.2"
num-complex = "0.4.1"
clap = { version = "3.1.18", features = ["derive"] }
